caddijp/frontend

- README.md
- package.json
fix repo name from styleguide to frontend
> styleguide to frontend

- .github/mergeable.yml
- .github/stale.yml
- package.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
- yarn.lock
Unexpectedly usable plugins ☺️
> feat: added prettier plugins

- lerna.json
- package.json
> fix: registry urls

- package.json
- packages/components/package.json
> fix: lint script

- CHANGELOG.md
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
* `components`
* [#9](https://github.com/caddijp/frontend/pull/9) fix: lint script ([@sottar](https://github.com/sottar))
> chore: bump v0.0.3

- packages/components/package.json
- packages/components/src/components/Upload/Upload.tsx
- packages/components/src/components/Upload/index.ts
- packages/components/src/components/Upload/interface.d.ts
- packages/components/src/index.ts
- yarn.lock
Since it takes a long time to implement it from scratch, just import and export [antd Upload component](https://ant.design/components/upload/#components-upload-demo-drag) for now.
> feat(components): upload component

- packages/components/src/components/Card/Card.tsx
- packages/components/src/components/Card/index.ts
- packages/components/src/index.ts
I want to create components as strictly and then make it flexibility if necessary
> feat(components): card component

- packages/components/src/components/Button/Button.tsx
> feat(components): button component

- packages/components/src/components/Form/Checkbox.tsx
- packages/components/src/components/Form/Input.tsx
- packages/components/src/components/Form/index.ts
- packages/components/src/index.ts
Input component
Checkbox component
> Feature form component

- packages/components/src/components/Alert/Caution.tsx
- packages/components/src/components/Alert/index.ts
- packages/components/src/index.ts
> feat(components): caution component

- CHANGELOG.md
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
- `components`
- [#15](https://github.com/caddijp/frontend/pull/15) feat(components): caution component ([@sottar](https://github.com/sottar))
- [#14](https://github.com/caddijp/frontend/pull/14) Feature form component ([@sottar](https://github.com/sottar))
- [#13](https://github.com/caddijp/frontend/pull/13) feat(components): button component ([@sottar](https://github.com/sottar))
- [#12](https://github.com/caddijp/frontend/pull/12) feat(components): card component ([@sottar](https://github.com/sottar))
- [#11](https://github.com/caddijp/frontend/pull/11) feat(components): upload component ([@sottar](https://github.com/sottar))
> chore: bump v0.0.4

- packages/components/src/Form/Checkbox.tsx
- packages/components/src/Form/Input.tsx
fix tiny css of checkbox and input component.
> fix: tiny design

- CHANGELOG.md
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
- `components`
- [#18](https://github.com/caddijp/frontend/pull/18) fix: tiny design ([@sottar](https://github.com/sottar))
> chore: bump v0.0.5

- packages/eslint-config/index.js
> chore(packages/eslint-config): add custom rules

- packages/components/src/Button/Button.tsx
- packages/components/src/Button/__snapshots__/story.storyshot
- packages/components/src/Button/story.tsx
- packages/components/src/Form/Input.tsx
> fix: style

- packages/components/src/Alert/Alert.tsx
- packages/components/src/Alert/index.ts
> feat: alert component

- CHANGELOG.md
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
* `components`
* [#27](https://github.com/caddijp/frontend/pull/27) fix: style ([@sottar](https://github.com/sottar))
* `components`
* [#28](https://github.com/caddijp/frontend/pull/28) feat: alert component ([@sottar](https://github.com/sottar))
* `eslint-config`
* [#25](https://github.com/caddijp/frontend/pull/25) chore(packages/eslint-config): add custom rules ([@9renpoto](https://github.com/9renpoto))
✨  Done in 10.94s.
> chore: bump v0.0.6

- packages/components/src/Button/Button.tsx
- packages/components/src/Form/Checkbox.tsx
> feat: text button component

- CHANGELOG.md
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
- `components`
- [#27](https://github.com/caddijp/frontend/pull/27) fix: style ([@sottar](https://github.com/sottar))
- `components`
- [#30](https://github.com/caddijp/frontend/pull/30) feat: text button component ([@sottar](https://github.com/sottar))
- [#26](https://github.com/caddijp/frontend/pull/26) Add TextArea component ([@enzinia](https://github.com/enzinia))
- [#28](https://github.com/caddijp/frontend/pull/28) feat: alert component ([@sottar](https://github.com/sottar))
- `components`, `eslint-config`, `stylelint-config`
- [#29](https://github.com/caddijp/frontend/pull/29) chore: bump v0.0.6 ([@sottar](https://github.com/sottar))
- `eslint-config`
- [#25](https://github.com/caddijp/frontend/pull/25) chore(packages/eslint-config): add custom rules …
> chore: bump v0.0.7

- CHANGELOG.md
- packages/components/README.md
- packages/eslint-config/README.md
- packages/stylelint-config/README.md
this generated changelog was incorrect and was regenerated.
Tag is required for generation.
> docs: re-generate changelogs

- packages/components/.storybook/config.tsx
- packages/components/.storybook/main.js
- packages/components/__tests__/Form/__snapshots__/TextArea.stories.storyshot
- packages/components/package.json
- yarn.lock
https://medium.com/storybookjs/zero-config-storybook-66e7c4798e5d#931f
https://medium.com/storybookjs/declarative-storybook-configuration-49912f77b78
`@storybook/addon-essentials` will gives us great experience 🎉
> Add @storybook/addon-essentials

- packages/components/__tests__/Table/__snapshots__/story.storyshot
- packages/components/src/Table/Table.tsx
- packages/components/src/Table/__snapshots__/story.storyshot
- packages/components/src/Table/index.ts
- packages/components/src/Table/story.tsx
- packages/components/src/index.ts
Added very basic Table component.
Support JSX.
Close #23
> feat: add table component

- package.json
- packages/components/babel.config.js
- packages/components/package.json
- yarn.lock
> chore: use ts-jest

- package.json
- packages/components/.storybook/antd.styles.js
- packages/components/.storybook/main.js
- packages/components/babel.config.js
- packages/components/package.json
- packages/components/src/Pagination/Pagination.tsx
- packages/components/src/Pagination/index.ts
- packages/components/src/Pagination/story.tsx
- packages/components/src/index.ts
- yarn.lock
Pagination ComponentをAntdのPagination Componentをラップする形で実装
AntdのstyleをStorybook上で当てることが出来ないため、
テストからは対象から外しています
#43 でIssue作成済み
> Pagination Componentを実装

- CHANGELOG.md
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
* `components`, `eslint-config`
* [#36](https://github.com/caddijp/frontend/pull/36) fix: stories glob ([@9renpoto](https://github.com/9renpoto))
* `components`
* [#42](https://github.com/caddijp/frontend/pull/42) Pagination Componentを実装 ([@scabyms](https://github.com/scabyms))
* [#46](https://github.com/caddijp/frontend/pull/46) feat: add antd styles ([@tkiryu](https://github.com/tkiryu))
* [#40](https://github.com/caddijp/frontend/pull/40) feat: add table component ([@enzinia](https://github.com/enzinia))
* [#33](https://github.com/caddijp/frontend/pull/33) impl modal component ([@scabyms](https://github.com/scabyms))
* [#34](https://github.com/caddijp/frontend/pull/34) Add @storybook/addon-essentials ([@tkiryu](https://github.com/tkiryu))
- Keisuke Kan …
> chore: bump v0.0.8

- CHANGELOG.md
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
* `components`
* [#48](https://github.com/caddijp/frontend/pull/48) fix: modal component ([@sottar](https://github.com/sottar))
> chore: bump v0.0.9

- packages/components/src/Modal/Modal.tsx
> fix: modal style

- CHANGELOG.md
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
* `components`
* [#53](https://github.com/caddijp/frontend/pull/53) fix: modal style ([@sottar](https://github.com/sottar))
* [#52](https://github.com/caddijp/frontend/pull/52) Feature/disable style for checkbox ([@sottar](https://github.com/sottar))
> chore: bump v0.0.11

- packages/components/src/Form/Checkbox.tsx
> fix: checkbox type

- CHANGELOG.md
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
* `components`
* [#55](https://github.com/caddijp/frontend/pull/55) fix: checkbox type ([@sottar](https://github.com/sottar))
> chore: bump v0.0.12

- packages/components/__tests__/Upload/__snapshots__/Upload.stories.storyshot
- packages/components/src/Upload/Upload.stories.tsx
- packages/components/src/Upload/Upload.tsx
Update the upload component for more flexibility
> Update upload component

- packages/components/src/Modal/Modal.tsx
Made the modal component more usuful
> feat: enhance modal component

- packages/components/src/Modal/Modal.tsx
> fix: modal component

- packages/components/__tests__/Button/__snapshots__/story.storyshot
- packages/components/src/Button/Button.tsx
- packages/components/src/Button/story.tsx
- added danger button
- added `filled` and `bordered` option (default will be a `filled`)
> update button component

- CHANGELOG.md
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
* `components`
* [#92](https://github.com/caddijp/frontend/pull/92) fix: modal component ([@sottar](https://github.com/sottar))
* `components`
* [#90](https://github.com/caddijp/frontend/pull/90) update button component ([@sottar](https://github.com/sottar))
* [#91](https://github.com/caddijp/frontend/pull/91) feat: enhance modal component ([@sottar](https://github.com/sottar))
> chore: bump v0.0.15

- packages/components/src/Form/Input.tsx
added some attributes to the button component.
> enhance button component

- CHANGELOG.md
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
- packages/tsconfig/package.json
* `components`
* [#130](https://github.com/caddijp/frontend/pull/130) enhance button component ([@sottar](https://github.com/sottar))
* `components`, `tsconfig`
* [#3](https://github.com/caddijp/frontend/pull/3) tsconfig base ([@9renpoto](https://github.com/9renpoto))
> chore: bump v0.0.16

- CHANGELOG.md
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
- packages/tsconfig/package.json
* [#132](https://github.com/caddijp/frontend/pull/132) Update yarn.lock ([@9renpoto](https://github.com/9renpoto))
> chore: bump v0.0.17

- package.json
- yarn.lock
> fix: pin @types/react and @types/react-dom

- README.md
- packages/components/README.md
- packages/components/tsconfig.json
- packages/eslint-config/README.md
- packages/stylelint-config/README.md
- packages/tsconfig/README.md
- packages/tsconfig/package.json
> docs(readme): added install and usage, inspred standard-readme

- packages/components/src/Notification/Notification.ts
- packages/components/src/Notification/index.ts
- packages/components/src/index.ts
> feat: add notifiaction component

- CHANGELOG.md
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
- packages/tsconfig/package.json
* `components`
* [#142](https://github.com/caddijp/frontend/pull/142) feat: add notifiaction component ([@sottar](https://github.com/sottar))
> chore: bump v0.0.18

- .github/workflows/nodejs.yml
- .yarnclean
- README.md
- packages/components/package.json
- packages/eslint-config/package.json
> refactor: collect coverage

- packages/components/src/Button/Button.tsx
> fix(packages/components): button props

- CHANGELOG.md
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
- packages/tsconfig/package.json
- `components`
- [#183](https://github.com/caddijp/frontend/pull/183) fix(packages/components): button props ([@9renpoto](https://github.com/9renpoto))
> docs: bump v0.1.1

- .github/workflows/size.yml
> feat: add compressed-size

- packages/components/.storybook/antd.styles.js
- packages/components/src/Notification/Notification.stories.tsx
- packages/components/src/Notification/Notification.ts
Add duration prop to Notification
> feat(packages/components): add duration prop to Notification

- .github/workflows/publish.yml
- package.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
- packages/tsconfig/package.json
github packages に ホストする
git のタグを切ったタイミングでそのバージョンの package を github packages に push する
> introduce github packages

- CHANGELOG.md
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
- packages/tsconfig/package.json
- `eslint-config`
- [#318](https://github.com/caddijp/frontend/pull/318) feat: add two rules to the eslint configuration ([@ksakiyama](https://github.com/ksakiyama))
- ksakiyama ([@ksakiyama](https://github.com/ksakiyama))
> Bump v0.3.0

- .github/workflows/publish.yml
- CHANGELOG.md
- lerna.json
- package-lock.json
- package.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
- packages/tsconfig/package.json
> Bump v0.4.0

- lerna.json
- package-lock.json
- package.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
- packages/tsconfig/package.json
> fix: publish failed (syntax error)

- .github/workflows/publish.yml
- lerna.json
- package-lock.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
- packages/tsconfig/package.json
> fix: registry-url

- .github/workflows/publish.yml
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
- packages/tsconfig/package.json
> Bump v0.4.3

- .github/workflows/publish.yml
- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
- packages/tsconfig/package.json
> Bump v0.4.4

- lerna.json
- packages/components/package.json
- packages/eslint-config/package.json
- packages/stylelint-config/package.json
- packages/tsconfig/package.json
> Bump v0.4.7
